//------------CLEAR REDUCER----------
export const CLEAR_DATA = 'CLEAR_DATA';
//------------MESSAGE----------------
export const RESET_MESSAGE = 'RESET_MESSAGE';
export const CREATE_SERVICE_REQUEST_SUCCESS = 'CREATE_SERVICE_REQUEST_SUCCESS';
export const CREATE_SERVICE_REQUEST_FAILURE = 'CREATE_SERVICE_REQUEST_FAILURE';
export const CREATE_CUSTOMER_ACCOUNT_SUCCESS =
  'CREATE_CUSTOMER_ACCOUNT_SUCCESS';
export const CREATE_CUSTOMER_ACCOUNT_FAILURE =
  'CREATE_CUSTOMER_ACCOUNT_FAILURE';
export const CANCEL_SERVICE_REQUEST_SUCCESS = 'CANCEL_SERVICE_REQUEST_SUCCESS';
export const CANCEL_SERVICE_REQUEST_FAILURE = 'CANCEL_SERVICE_REQUEST_FAILURE';
//------------SERVICE----------------
export const GET_ALL_SERVICE = 'GET_ALL_SERVICE';
export const RESET_SERVICE_REQUEST = 'RESET_SERVICE_REQUEST';
export const RESET_REQUEST_DETAIL = 'RESET_REQUEST_DETAIL';
export const GET_REQUEST_SERVICE_DETAILS_BY_REQUEST_SERVICE_ID =
  'GET_REQUEST_SERVICE_DETAILS_BY_REQUEST_SERVICE_ID';
export const GET_SERVICE_REQUEST_BY_USER_ID_AND_STATUS =
  'GET_SERVICE_REQUEST_BY_USER_ID_AND_STATUS';
export const CANCEL_REQUEST_SERVICE = 'CANCEL_REQUEST_SERVICE';
//------------USER----------------
export const GET_OTP = 'GET_OTP';
export const GET_USER = 'GET_USER';
export const RESET_USER_MESSAGE = 'RESET_USER_MESSAGE';
export const ACCOUNT_HAVE_BEEN_BANNED = 'ACCOUNT_HAVE_BEEN_BANNED';
export const GET_USER_INFORMATION = 'GET_USER_INFORMATION';
export const UPDATE_INFORMATION_SUCCESS = 'UPDATE_INFORMATION_SUCCESS';
export const UPDATE_INFORMATION_FAILURE = 'UPDATE_INFORMATION_FAILURE';
//------------CONTRACT------------
export const APPROVE_CONTRACT_SUCCESS = 'APPROVE_CONTRACT_SUCCESS';
export const APPROVE_CONTRACT_FAILURE = 'APPROVE_CONTRACT_FAILURE';
export const REQUEST_UPDATE_CONTRACT_SUCCESS =
  'REQUEST_UPDATE_CONTRACT_SUCCESS';
export const REQUEST_UPDATE_CONTRACT_FAILURE =
  'REQUEST_UPDATE_CONTRACT_FAILURE';
export const UPDATE_STATUS_REQUEST_SERVICE_DETAIL_SUCCESS =
  'UPDATE_STATUS_REQUEST_SERVICE_DETAIL_SUCCESS';
export const UPDATE_STATUS_REQUEST_SERVICE_DETAIL_FAILURE =
  'UPDATE_STATUS_REQUEST_SERVICE_DETAIL_FAILURE';
export const GET_CONTRACT_BY_SERVICE_REQUEST_ID =
  'GET_CONTRACT_BY_SERVICE_REQUEST_ID';
export const GET_CONTRACT_PARENT_BY_SERVICE_REQUEST_REFERENCE =
  'GET_CONTRACT_PARENT_BY_SERVICE_REQUEST_REFERENCE';
export const RESET_CONTRACT_PARENT = 'RESET_CONTRACT_PARENT';
//------------INVOICE------------
export const GET_INFORMATION_INVOICE_BY_REQUEST_SERVICE_ID =
  'GET_INFORMATION_INVOICE_BY_REQUEST_SERVICE_ID';
export const RESET_INVOICE = 'RESET_INVOICE';
//------------PROMOTION------------
export const GET_ALL_PROMOTION_VALID_BY_USER_ID =
  'GET_ALL_PROMOTION_VALID_BY_USER_ID';
export const GET_INFORMATION_PROMOTION_BY_ID =
  'GET_INFORMATION_PROMOTION_BY_ID';
//------------INVITE CODE------------/
export const GET_INVITE_CODE = 'GET_INVITE_CODE';
export const RESET_INVITE_CODE = 'RESET_INVITE_CODE';
export const INVALID_INVITE_CODE = 'INVALID_INVITE_CODE';
