//-------------CLEAR DATA--------------
export const CLEAR_DATA = 'CLEAR_DATA';
//-------------MESSAGE--------------
export const RESET_MESSAGE = 'RESET_MESSAGE';
export const INSERT_REQUEST_MATERIAL_SUCCESS =
  'INSERT_REQUEST_MATERIAL_SUCCESS';
export const INSERT_REQUEST_MATERIAL_FAILURE =
  'INSERT_REQUEST_MATERIAL_FAILURE';
export const CREATE_REPORT_SUCCESS = 'CREATE_REPORT_SUCCESS';
export const CREATE_REPORT_FAILURE = 'CREATE_REPORT_FAILURE';
export const CANCEL_REQUEST_MATERIAL_SUCCESS =
  'CANCEL_REQUEST_MATERIAL_SUCCESS';
export const CANCEL_REQUEST_MATERIAL_FAILURE =
  'CANCEL_REQUEST_MATERIAL_FAILURE';
//------------SERVICE----------------
export const GET_ALL_REQUEST_SERVICE_BY_WORKER_ID =
  'GET_ALL_REQUEST_SERVICE_BY_WORKER_ID';
export const RESET_REQUEST_DETAIL = 'RESET_REQUEST_DETAIL';
export const GET_REQUEST_SERVICE_DETAILS_BY_REQUEST_SERVICE_ID_AND_WORKER_ID =
  'GET_REQUEST_SERVICE_DETAILS_BY_REQUEST_SERVICE_ID_AND_WORKER_ID';
//------------USER----------------
export const GET_OTP = 'GET_OTP';
export const GET_USER_INFO = 'GET_USER_INFO';
//------------MATERIAL----------------
export const GET_ALL_MATERIAL_BY_REQUEST_DETAIL_ID =
  'GET_ALL_MATERIAL_BY_REQUEST_DETAIL_ID';
export const RESET_USED_MATERIAL_STATE = 'RESET_USED_MATERIAL_STATE';
export const GET_ALL_MATERIAL = 'GET_ALL_MATERIAL';
//------------REPORT----------------
export const GET_ALL_REPORT_BY_REQUEST_DETAIL_ID =
  'GET_ALL_REPORT_BY_REQUEST_DETAIL_ID';
export const RESET_REPORT_STATE = 'RESET_REPORT_STATE';
