//------------CLEAR REDUCER----------
export const CLEAR_DATA = 'CLEAR_DATA';
//------------MESSAGE----------------
export const RESET_MESSAGE = 'RESET_MESSAGE';
export const CREATE_REQUEST_SERVICE_SUCCESS = 'CREATE_REQUEST_SERVICE_SUCCESS';
export const CREATE_REQUEST_SERVICE_FAILURE = 'CREATE_REQUEST_SERVICE_FAILURE';
export const CREATE_CUSTOMER_ACCOUNT_SUCCESS =
  'CREATE_CUSTOMER_ACCOUNT_SUCCESS';
export const CREATE_CUSTOMER_ACCOUNT_FAILURE =
  'CREATE_CUSTOMER_ACCOUNT_FAILURE';
export const CANCEL_REQUEST_SERVICE_SUCCESS = 'CANCEL_REQUEST_SERVICE_SUCCESS';
export const CANCEL_REQUEST_SERVICE_FAILURE = 'CANCEL_REQUEST_SERVICE_FAILURE';
//------------SERVICE----------------
export const GET_ALL_SERVICE = 'GET_ALL_SERVICE';
export const GET_ALL_REQUEST_SERVICE_BY_USER_ID =
  'GET_ALL_REQUEST_SERVICE_BY_USER_ID';
export const RESET_REQUEST_SERVICE = 'RESET_REQUEST_SERVICE';
export const RESET_REQUEST_DETAIL = 'RESET_REQUEST_DETAIL';
export const GET_REQUEST_SERVICE_DETAILS_BY_REQUEST_SERVICE_ID =
  'GET_REQUEST_SERVICE_DETAILS_BY_REQUEST_SERVICE_ID';
export const GET_REQUEST_SERVICE_BY_USER_ID_AND_STATUS =
  'GET_REQUEST_SERVICE_BY_USER_ID_AND_STATUS';
export const CANCEL_REQUEST_SERVICE = 'CANCEL_REQUEST_SERVICE';
//------------USER----------------
export const GET_OTP = 'GET_OTP';
export const GET_USER_INFO = 'GET_USER_INFO';
//------------CONTRACT------------
export const GET_CONTRACT_LIST_BY_USER_ID = 'GET_CONTRACT_LIST_BY_USER_ID';
export const APPROVE_CONTRACT_SUCCESS = 'APPROVE_CONTRACT_SUCCESS';
export const APPROVE_CONTRACT_FAILURE = 'APPROVE_CONTRACT_FAILURE';
export const REQUEST_UPDATE_CONTRACT_SUCCESS =
  'REQUEST_UPDATE_CONTRACT_SUCCESS';
export const REQUEST_UPDATE_CONTRACT_FAILURE =
  'REQUEST_UPDATE_CONTRACT_FAILURE';
export const UPDATE_STATUS_REQUEST_SERVICE_DETAIL_SUCCESS =
  'UPDATE_STATUS_REQUEST_SERVICE_DETAIL_SUCCESS';
export const UPDATE_STATUS_REQUEST_SERVICE_DETAIL_FAILURE =
  'UPDATE_STATUS_REQUEST_SERVICE_DETAIL_FAILURE';
//------------INVOICE------------GetInfomationInvoiceByRequestServiceID
export const GET_INFORMATION_INVOICE_BY_REQUEST_SERVICE_ID =
  'GET_INFORMATION_INVOICE_BY_REQUEST_SERVICE_ID';
export const RESET_INVOICE = 'RESET_INVOICE';
